/**
 * Shared fixture data for frontend tests.
 */

import type {
  Project,
  Chapter,
  Scene,
  Beat,
  Character,
  Location,
  ReferenceItem,
  AppSettings,
} from "../lib/types";

const now = new Date().toISOString();

export const mockProject: Project = {
  id: "proj-ember-ash",
  name: "Ember & Ash",
  source_type: "Plottr",
  source_path: "/mock/path/story.pltr",
  created_at: now,
  modified_at: now,
  author_pen_name: "J. Smith",
  genre: "Fantasy",
  description: "A tale of two siblings bound by fire and memory.",
  word_target: 80000,
  reference_types: ["characters", "locations", "items", "objectives", "organizations"],
  project_type: "novel",
  target_page_count: null,
};

export const mockChapters: Chapter[] = [
  {
    id: "ch-1",
    project_id: "proj-ember-ash",
    title: "Part One: Embers",
    position: 0,
    source_id: null,
    archived: false,
    locked: false,
    is_part: true,
    synopsis: null,
    planning_status: "fixed",
  },
  {
    id: "ch-2",
    project_id: "proj-ember-ash",
    title: "The Awakening",
    position: 1,
    source_id: null,
    archived: false,
    locked: false,
    is_part: false,
    synopsis: null,
    planning_status: "fixed",
  },
  {
    id: "ch-3",
    project_id: "proj-ember-ash",
    title: "First Flame",
    position: 2,
    source_id: null,
    archived: false,
    locked: false,
    is_part: false,
    synopsis: null,
    planning_status: "fixed",
  },
  {
    id: "ch-4",
    project_id: "proj-ember-ash",
    title: "Part Two: Ash",
    position: 3,
    source_id: null,
    archived: false,
    locked: false,
    is_part: true,
    synopsis: null,
    planning_status: "fixed",
  },
  {
    id: "ch-5",
    project_id: "proj-ember-ash",
    title: "The Fall",
    position: 4,
    source_id: null,
    archived: false,
    locked: false,
    is_part: false,
    synopsis: null,
    planning_status: "fixed",
  },
  {
    id: "ch-6",
    project_id: "proj-ember-ash",
    title: "Rekindled",
    position: 5,
    source_id: null,
    archived: false,
    locked: false,
    is_part: false,
    synopsis: null,
    planning_status: "fixed",
  },
];

export const mockScenes: Scene[] = [
  {
    id: "sc-1",
    chapter_id: "ch-2",
    title: "The Village",
    synopsis: "Ember wakes in her childhood home, unaware of the changes to come.",
    prose: null,
    position: 0,
    source_id: null,
    archived: false,
    locked: false,
    scene_type: "normal",
    scene_status: "draft",
    planning_status: "fixed",
    editor_mode: "beat",
  },
  {
    id: "sc-2",
    chapter_id: "ch-2",
    title: "The Stranger",
    synopsis: "A traveler arrives with news that will alter everything.",
    prose: null,
    position: 1,
    source_id: null,
    archived: false,
    locked: false,
    scene_type: "normal",
    scene_status: "draft",
    planning_status: "fixed",
    editor_mode: "beat",
  },
  {
    id: "sc-3",
    chapter_id: "ch-3",
    title: "The Gift",
    synopsis: "Ember receives the family heirloom and discovers its power.",
    prose: null,
    position: 0,
    source_id: null,
    archived: false,
    locked: false,
    scene_type: "normal",
    scene_status: "draft",
    planning_status: "fixed",
    editor_mode: "beat",
  },
  {
    id: "sc-4",
    chapter_id: "ch-3",
    title: "First Spark",
    synopsis: "The first flame ignites—both literal and metaphorical.",
    prose: null,
    position: 1,
    source_id: null,
    archived: false,
    locked: false,
    scene_type: "normal",
    scene_status: "draft",
    planning_status: "fixed",
    editor_mode: "beat",
  },
  {
    id: "sc-5",
    chapter_id: "ch-5",
    title: "The Betrayal",
    synopsis: "Ash makes a choice that will haunt both siblings.",
    prose: null,
    position: 0,
    source_id: null,
    archived: false,
    locked: false,
    scene_type: "normal",
    scene_status: "draft",
    planning_status: "fixed",
    editor_mode: "beat",
  },
  {
    id: "sc-6",
    chapter_id: "ch-5",
    title: "Embers Fade",
    synopsis: "The aftermath of loss and the long road to forgiveness.",
    prose: null,
    position: 1,
    source_id: null,
    archived: false,
    locked: false,
    scene_type: "normal",
    scene_status: "draft",
    planning_status: "fixed",
    editor_mode: "beat",
  },
  {
    id: "sc-7",
    chapter_id: "ch-6",
    title: "The Reunion",
    synopsis: "Brother and sister meet again, changed by time and fire.",
    prose: null,
    position: 0,
    source_id: null,
    archived: false,
    locked: false,
    scene_type: "normal",
    scene_status: "draft",
    planning_status: "fixed",
    editor_mode: "beat",
  },
  {
    id: "sc-8",
    chapter_id: "ch-6",
    title: "New Flame",
    synopsis: "Together they light a fire that will warm the kingdom.",
    prose: null,
    position: 1,
    source_id: null,
    archived: false,
    locked: false,
    scene_type: "normal",
    scene_status: "draft",
    planning_status: "fixed",
    editor_mode: "beat",
  },
];

export const mockBeats: Beat[] = [
  {
    id: "beat-1",
    scene_id: "sc-1",
    content: "Ember wakes at dawn, disoriented.",
    prose:
      "The first light crept through the shutters, painting stripes across the worn floorboards.",
    position: 0,
  },
  {
    id: "beat-2",
    scene_id: "sc-1",
    content: "She notices something is wrong with the village.",
    prose: null,
    position: 1,
  },
  {
    id: "beat-3",
    scene_id: "sc-2",
    content: "A hooded figure approaches the inn.",
    prose: "The stranger moved like smoke, barely disturbing the dust.",
    position: 0,
  },
  {
    id: "beat-4",
    scene_id: "sc-2",
    content: "The stranger reveals they know Ember's name.",
    prose: null,
    position: 1,
  },
  {
    id: "beat-5",
    scene_id: "sc-3",
    content: "Grandmother hands Ember the family locket.",
    prose: null,
    position: 0,
  },
  {
    id: "beat-6",
    scene_id: "sc-3",
    content: "Ember feels warmth when she touches it.",
    prose: "A current ran through her fingers—not heat, but something older.",
    position: 1,
  },
  {
    id: "beat-7",
    scene_id: "sc-4",
    content: "Ember tries to light a candle with her hands.",
    prose: null,
    position: 0,
  },
  {
    id: "beat-8",
    scene_id: "sc-4",
    content: "The flame ignites—small but real.",
    prose: "It flickered, uncertain, then steadied. Her breath caught.",
    position: 1,
  },
  {
    id: "beat-9",
    scene_id: "sc-5",
    content: "Ash confronts Ember about the power.",
    prose: null,
    position: 0,
  },
  {
    id: "beat-10",
    scene_id: "sc-5",
    content: "Ash makes a deal with the wrong people.",
    prose: null,
    position: 1,
  },
  {
    id: "beat-11",
    scene_id: "sc-6",
    content: "Ember flees the village alone.",
    prose: "She did not look back. The smoke followed anyway.",
    position: 0,
  },
  {
    id: "beat-12",
    scene_id: "sc-6",
    content: "Years pass; Ember builds a new life.",
    prose: null,
    position: 1,
  },
  {
    id: "beat-13",
    scene_id: "sc-7",
    content: "Ember receives a letter from Ash.",
    prose: null,
    position: 0,
  },
  {
    id: "beat-14",
    scene_id: "sc-7",
    content: "They meet at the old bridge.",
    prose: "The river had changed its course. They had not.",
    position: 1,
  },
  {
    id: "beat-15",
    scene_id: "sc-8",
    content: "Ember and Ash combine their flames.",
    prose: null,
    position: 0,
  },
  {
    id: "beat-16",
    scene_id: "sc-8",
    content: "The kingdom sees the new light for the first time.",
    prose: "It was not the sun. It was something better.",
    position: 1,
  },
];

export const mockCharacters: Character[] = [
  {
    id: "char-1",
    project_id: "proj-ember-ash",
    name: "Ember",
    description: "The younger sibling, gifted with fire magic.",
    attributes: { Age: "22", Role: "Protagonist", Element: "Fire" },
    source_id: null,
  },
  {
    id: "char-2",
    project_id: "proj-ember-ash",
    name: "Ash",
    description: "The older sibling, burdened by choices.",
    attributes: { Age: "26", Role: "Antagonist-turned-ally", Element: "Ash" },
    source_id: null,
  },
  {
    id: "char-3",
    project_id: "proj-ember-ash",
    name: "Grandmother",
    description: "Keeper of the family secrets.",
    attributes: { Age: "78", Role: "Mentor" },
    source_id: null,
  },
];

export const mockLocations: Location[] = [
  {
    id: "loc-1",
    project_id: "proj-ember-ash",
    name: "The Village of Hearth",
    description: "A small farming community where Ember and Ash grew up.",
    attributes: { Type: "Village", Climate: "Temperate", Region: "Northern Vale" },
    source_id: null,
  },
  {
    id: "loc-2",
    project_id: "proj-ember-ash",
    name: "The Old Bridge",
    description: "A stone bridge over the river where the siblings used to play.",
    attributes: { Type: "Landmark", Condition: "Weathered" },
    source_id: null,
  },
];

export const mockReferenceItems: ReferenceItem[] = [
  {
    id: "ref-1",
    project_id: "proj-ember-ash",
    reference_type: "items",
    name: "The Family Locket",
    description: "A silver locket that amplifies fire magic.",
    attributes: { Origin: "Ancestral", Power: "Amplification" },
    source_id: null,
  },
  {
    id: "ref-2",
    project_id: "proj-ember-ash",
    reference_type: "objectives",
    name: "Protect the Village",
    description: "Ember's driving goal after the betrayal.",
    attributes: { Priority: "High", Status: "Active" },
    source_id: null,
  },
  {
    id: "ref-3",
    project_id: "proj-ember-ash",
    reference_type: "objectives",
    name: "Reconcile with Ash",
    description: "The emotional core of the second act.",
    attributes: { Priority: "High", Status: "Resolved" },
    source_id: null,
  },
];

export const mockAppSettings: AppSettings = {
  author_name: "J. Smith",
  contact_address_line1: "123 Writer's Lane",
  contact_address_line2: "Portland, OR 97201",
  contact_phone: null,
  contact_email: "j.smith@example.com",
};
